### ISSUE TITLE
RM69330 Demo

### ISSUE THREAD

**Issue by WrelksMC** [kotocom/PV13904PY24G#1]
Hello, I am currently working on getting a rm69330 screen to work and I'm coming across a lot of trouble. this is like the only repository I could find about this driving ic that claims to work. Could you upload pictures of this screen actually working. Also, I'd be willing to purchase the STM board & screen / any other components required to get it to work if you are willing to sell it that is, (fine with throwing in a little extra). Apologies for opening an issue, didn't know where else to put this. 

All the best.

**Comment by kotocom** [comment]
In the /doc section you can find videos, including the display working [ProgResult.mp4](https://github.com/kotocom/PV13904PY24G/blob/main/doc/ProgResult.mp4)

Here's some images of the process: https://www.instagram.com/p/CHx9_zIrINF/

I also believe that you don't need the board I used, just repeat the Init SEQ [(doc/OLED_INIT_SEQUENCE.txt](https://github.com/kotocom/PV13904PY24G/blob/b8b0f006c7a4433668a1bc7547cab492383d856c/doc/OLED_INIT_SEQUENCE.txt)) and learn from basic function that fills the display buffer.

**Comment by WrelksMC** [comment]
Wow, thank you! This is immensely helpful, if there is one more thing I could ask however - do you have a complete wiring diagram for this project?

**Comment by kotocom** [comment]
> Wow, thank you! This is immensely helpful, if there is one more thing I could ask however - do you have a complete wiring diagram for this project?

I didn't do the diagram for the project, but have found a draft of the connector that I did to connect the MCU board. You can figure out what pins I drive from the SPI and https://github.com/kotocom/PV13904PY24G/blob/b8b0f006c7a4433668a1bc7547cab492383d856c/modules/source/display.cpp

Don't forget that the display IC operating voltage is 1.8V level logic, therefore you can use simple resistor divider for some one-directional signals 3.3V/2 = 1.65, but for other way around you'd need something with transistor or use low power MCU board with 1.8V supply.

![Disp_pinout](https://github.com/kotocom/PV13904PY24G/assets/34425933/a57125e6-a5f5-4d5c-b02e-c2ee6e2fa596)

**Comment by WrelksMC** [comment]
Thank you so much, you have no idea how immensly useful all of this has been 😅. I was wondering if it would be possible though to potnetially hire you to recreate a demo for a rm69330 screen, I messaged you on instagram my offer and the details of the job, let me know what you think.

**Comment by WrelksMC** [comment]
Don't mean to be a bother, but I'm super close to getting my own personal demo working. Screen flickers but I can't get it to display anything else. Sent my stuff over ig.

**Comment by hamedbagherii** [comment]
@kotocom  
Thanks for sharing the code and wiring.
I just wanted to make sure about some wiring. Does LCD SPI work with 3.3V or should it be used with a voltage divider?
X_RES and VCI_EN are connected to the microcontroller using a Voltage Divider(resistor).
Thanks

**Comment by kotocom** [comment]
> @kotocom Thanks for sharing the code and wiring. I just wanted to make sure about some wiring. Does LCD SPI work with 3.3V or should it be used with a voltage divider? X_RES and VCI_EN are connected to the microcontroller using a Voltage Divider(resistor). Thanks

Hello there. Disp doesn't work with 3.3V, I just used the divider for these, the display documentation stated all signals 1.8V, and only the Vbat is the Li-ion/pol V range.

p.s. Regardless, with the divider it still works fine with 50Mhz SPI clock speed, no worries.
